version: "3.8"
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - /docker/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      - arr

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - /docker/radarr:/config
      - /docker/mounts/movies:/movies
      - /docker/mounts/completed:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - arr

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - /docker/sonarr/:/config
      - /docker/mounts/tvshows:/tv
      - /docker/mounts/completed/:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - arr

networks:
  arr:
     external: true