version: "3.8"
services:
  jallyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
      - AUTO_UPDATE=true
    ports:
      - 9117:9117
    volumes:
      - <path to data>:/config
      - <path to blackhole>:/downloads
    restart: unless-stopped
